server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/legendsdb?serverTimezone=UTC
    username: jeanne
    password: admin
    driver_class_name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true